name: mindsnap
description: A Flutter app  project to manage mindful activities and social media goals.




version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.0
  hooks_riverpod: ^2.4.0
  flutter_hooks: ^0.20.0

  # Networking
  dio: ^5.3.1

  # Navigation
  go_router: ^7.0.1

  # UI & Utility
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Add assets if you have any (e.g., images, icons)
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # Add fonts if needed
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
